-- Офис и рабочее место
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'office', 'офис', ARRAY['Go to the office.', 'Office hours.', 'Home office.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'office');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'desk', 'письменный стол', ARRAY['Sit at your desk.', 'Clean desk policy.', 'Desk drawer.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'desk');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'chair', 'стул, кресло', ARRAY['Office chair.', 'Comfortable chair.', 'Swivel chair.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'chair');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'laptop', 'ноутбук', ARRAY['Use your laptop.', 'Laptop bag.', 'Company laptop.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'laptop');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'keyboard', 'клавиатура', ARRAY['Wireless keyboard.', 'Type on keyboard.', 'Keyboard shortcut.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'keyboard');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'mouse', 'мышь (компьютерная)', ARRAY['Computer mouse.', 'Click the mouse.', 'Wireless mouse.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'mouse');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'screen', 'экран', ARRAY['Screen brightness.', 'Dual screen setup.', 'Touch screen.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'screen');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'monitor', 'монитор', ARRAY['External monitor.', 'Monitor stand.', 'Second monitor.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'monitor');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'printer', 'принтер', ARRAY['Use the printer.', 'Printer is out of paper.', 'Color printer.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'printer');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'scanner', 'сканер', ARRAY['Scan with scanner.', 'Document scanner.', 'Flatbed scanner.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'scanner');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'phone', 'телефон', ARRAY['Office phone.', 'Phone extension.', 'Phone system.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'phone');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'document', 'документ', ARRAY['Important document.', 'Sign the document.', 'Document folder.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'document');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'folder', 'папка', ARRAY['Create new folder.', 'Project folder.', 'Folder structure.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'folder');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'stationery', 'канцелярские принадлежности', ARRAY['Office stationery.', 'Stationery cupboard.', 'Order stationery.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'stationery');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'business_office', 'pen', 'ручка', ARRAY['Write with pen.', 'Borrow a pen.', 'Ballpoint pen.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'business_office' AND english_word = 'pen');

-- Покупки и магазины  
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'shop', 'магазин', ARRAY['Go to the shop.', 'Shop online.', 'Coffee shop.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'shop');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'store', 'магазин', ARRAY['Department store.', 'Grocery store.', 'Store hours.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'store');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'market', 'рынок', ARRAY['Farmers market.', 'Market day.', 'Street market.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'market');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'supermarket', 'супермаркет', ARRAY['Shop at supermarket.', 'Supermarket chain.', 'Supermarket aisle.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'supermarket');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'mall', 'торговый центр', ARRAY['Shopping mall.', 'Mall parking.', 'Go to the mall.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'mall');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'shopping', 'покупки', ARRAY['Go shopping.', 'Shopping list.', 'Shopping bag.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'shopping');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'buy', 'покупать', ARRAY['Buy groceries.', 'Buy online.', 'Buy in bulk.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'buy');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'purchase', 'покупка, покупать', ARRAY['Make a purchase.', 'Purchase history.', 'Recent purchase.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'purchase');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'sell', 'продавать', ARRAY['Sell products.', 'For sale.', 'Sell online.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'sell');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'price', 'цена', ARRAY['Good price.', 'Price tag.', 'Ask the price.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'price');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'cost', 'стоимость, стоить', ARRAY['How much does it cost?', 'Cost of living.', 'Total cost.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'cost');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'expensive', 'дорогой', ARRAY['Too expensive.', 'Expensive taste.', 'Very expensive.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'expensive');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'cheap', 'дешёвый', ARRAY['Cheap price.', 'Buy cheap.', 'Cheap quality.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'cheap');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'bargain', 'выгодная покупка', ARRAY['Great bargain.', 'Bargain price.', 'Bargain hunter.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'bargain');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'everyday_shopping', 'discount', 'скидка', ARRAY['Student discount.', 'Discount code.', '20% discount.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'everyday_shopping' AND english_word = 'discount');
