-- Собеседование
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'job', 'работа', ARRAY['Looking for a job.', 'Job application.', 'Dream job.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'job');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'position', 'должность', ARRAY['Apply for position.', 'Open position.', 'Senior position.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'position');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'vacancy', 'вакансия', ARRAY['Job vacancy.', 'Fill vacancy.', 'Vacancy announcement.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'vacancy');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'career', 'карьера', ARRAY['Career development.', 'Career path.', 'Career goals.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'career');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'employment', 'трудоустройство', ARRAY['Full employment.', 'Employment contract.', 'Employment history.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'employment');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'interview', 'собеседование', ARRAY['Job interview.', 'Interview questions.', 'Phone interview.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'interview');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'candidate', 'кандидат', ARRAY['Job candidate.', 'Ideal candidate.', 'Interview candidate.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'candidate');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'applicant', 'соискатель', ARRAY['Job applicant.', 'Applicant pool.', 'Review applicant.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'applicant');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'resume', 'резюме', ARRAY['Send resume.', 'Update resume.', 'Resume template.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'resume');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'CV', 'резюме (curriculum vitae)', ARRAY['Submit CV.', 'CV format.', 'Professional CV.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'CV');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'experience', 'опыт', ARRAY['Work experience.', 'Years of experience.', 'Relevant experience.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'experience');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'skill', 'навык', ARRAY['Technical skills.', 'Soft skills.', 'Skill set.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'skill');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'qualification', 'квалификация', ARRAY['Educational qualification.', 'Professional qualification.', 'Required qualification.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'qualification');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'salary', 'зарплата', ARRAY['Annual salary.', 'Salary range.', 'Negotiate salary.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'salary');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_interview', 'hire', 'нанимать', ARRAY['Hire employees.', 'Hiring process.', 'Get hired.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_interview' AND english_word = 'hire');

-- Рабочая коммуникация
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'colleague', 'коллега', ARRAY['My colleague helped me.', 'Colleague from IT.', 'Work with colleagues.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'colleague');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'coworker', 'сотрудник', ARRAY['Friendly coworker.', 'Coworker relationship.', 'Help coworker.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'coworker');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'teammate', 'член команды', ARRAY['Great teammate.', 'Teammate collaboration.', 'Support teammate.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'teammate');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'boss', 'начальник', ARRAY['Talk to boss.', 'Boss approval.', 'Report to boss.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'boss');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'supervisor', 'руководитель', ARRAY['Immediate supervisor.', 'Supervisor feedback.', 'Supervisor meeting.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'supervisor');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'manager', 'менеджер', ARRAY['Project manager.', 'Manager role.', 'Speak to manager.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'manager');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'director', 'директор', ARRAY['Company director.', 'Board of directors.', 'Director meeting.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'director');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'employee', 'сотрудник', ARRAY['Company employee.', 'Employee benefits.', 'Employee handbook.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'employee');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'team', 'команда', ARRAY['Team meeting.', 'Team member.', 'Team work.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'team');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'department', 'отдел', ARRAY['HR department.', 'Department head.', 'Sales department.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'department');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'company', 'компания', ARRAY['Work for company.', 'Company policy.', 'Company culture.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'company');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'project', 'проект', ARRAY['New project.', 'Project deadline.', 'Project manager.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'project');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'task', 'задача', ARRAY['Complete task.', 'Task list.', 'Assign task.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'task');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'feedback', 'обратная связь', ARRAY['Give feedback.', 'Positive feedback.', 'Feedback form.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'feedback');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'work_communication', 'support', 'поддержка', ARRAY['Tech support.', 'Support team.', 'Customer support.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'work_communication' AND english_word = 'support');
