-- Медицина и здоровье
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'doctor', 'врач', ARRAY['See a doctor.', 'Family doctor.', 'Doctor appointment.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'doctor');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'hospital', 'больница', ARRAY['Go to hospital.', 'Hospital ward.', 'Hospital visit.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'hospital');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'clinic', 'клиника', ARRAY['Medical clinic.', 'Dental clinic.', 'Visit clinic.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'clinic');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'patient', 'пациент', ARRAY['Patient care.', 'New patient.', 'Patient history.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'patient');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'medicine', 'лекарство', ARRAY['Take medicine.', 'Prescription medicine.', 'Medicine cabinet.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'medicine');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'pain', 'боль', ARRAY['Feel pain.', 'Pain relief.', 'Sharp pain.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'pain');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'sick', 'больной', ARRAY['Feel sick.', 'Sick leave.', 'Get sick.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'sick');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'ill', 'больной', ARRAY['Seriously ill.', 'Fall ill.', 'Ill health.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'ill');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'health', 'здоровье', ARRAY['Good health.', 'Health insurance.', 'Public health.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'health');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'treatment', 'лечение', ARRAY['Medical treatment.', 'Treatment plan.', 'Under treatment.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'treatment');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'prescription', 'рецепт (медицинский)', ARRAY['Doctor prescription.', 'Prescription medicine.', 'Fill prescription.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'prescription');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'symptom', 'симптом', ARRAY['Flu symptoms.', 'Show symptoms.', 'Common symptom.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'symptom');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'fever', 'лихорадка, жар', ARRAY['High fever.', 'Fever reducer.', 'Have fever.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'fever');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'cough', 'кашель', ARRAY['Bad cough.', 'Cough medicine.', 'Cough syrup.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'cough');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'health_medical', 'headache', 'головная боль', ARRAY['Severe headache.', 'Headache relief.', 'Have headache.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'health_medical' AND english_word = 'headache');

-- Спорт и активности
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'sport', 'спорт', ARRAY['Play sport.', 'Favorite sport.', 'Sport activities.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'sport');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'game', 'игра', ARRAY['Football game.', 'Play game.', 'Win the game.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'game');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'player', 'игрок', ARRAY['Football player.', 'Team player.', 'Best player.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'player');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'coach', 'тренер', ARRAY['Team coach.', 'Coach training.', 'Hire coach.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'coach');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'training', 'тренировка', ARRAY['Training session.', 'Daily training.', 'Training program.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'training');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'exercise', 'упражнение', ARRAY['Physical exercise.', 'Exercise routine.', 'Do exercise.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'exercise');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'fitness', 'фитнес', ARRAY['Fitness club.', 'Fitness training.', 'Physical fitness.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'fitness');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'gym', 'тренажёрный зал', ARRAY['Go to gym.', 'Gym membership.', 'Home gym.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'gym');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'run', 'бегать', ARRAY['Morning run.', 'Run daily.', 'Run fast.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'run');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'swim', 'плавать', ARRAY['Swim in pool.', 'Learn to swim.', 'Swim team.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'swim');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'play', 'играть', ARRAY['Play football.', 'Play tennis.', 'Play sports.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'play');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'match', 'матч', ARRAY['Football match.', 'Watch match.', 'Match result.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'match');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'competition', 'соревнование', ARRAY['Sports competition.', 'Win competition.', 'International competition.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'competition');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'winner', 'победитель', ARRAY['Match winner.', 'Competition winner.', 'Declare winner.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'winner');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'sports_activities', 'score', 'счёт, забивать гол', ARRAY['Final score.', 'Score a goal.', 'Keep score.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'sports_activities' AND english_word = 'score');
