-- Слова для набора: Гостиница и проживание
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'hotel', 'гостиница', ARRAY['I stayed at a nice hotel.', 'The hotel has a pool.', 'Book a hotel room.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'hotel');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'room', 'номер, комната', ARRAY['My room is on the 5th floor.', 'Double room please.', 'Clean the room.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'room');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'reservation', 'бронирование', ARRAY['Make a reservation.', 'Cancel reservation.', 'Reservation confirmed.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'reservation');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'booking', 'бронь', ARRAY['Online booking available.', 'Booking reference number.', 'Change booking.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'booking');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'reception', 'стойка регистрации', ARRAY['Ask at reception.', 'Reception is open 24/7.', 'Reception desk.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'reception');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'key', 'ключ', ARRAY['Room key please.', 'Lost my key.', 'Key card system.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'key');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'lobby', 'вестибюль', ARRAY['Meet in the lobby.', 'Lobby bar.', 'Wait in lobby.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'lobby');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'single', 'одноместный номер', ARRAY['Single room for one night.', 'Single bed.', 'Single occupancy.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'single');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'double', 'двухместный номер', ARRAY['Double room with bath.', 'Double bed.', 'Double occupancy.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'double');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'suite', 'люкс', ARRAY['Presidential suite.', 'Honeymoon suite.', 'Suite with balcony.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'suite');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'floor', 'этаж', ARRAY['Which floor?', 'Ground floor.', 'Top floor.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'floor');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'elevator', 'лифт', ARRAY['Take the elevator.', 'Elevator is broken.', 'Use elevator.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'elevator');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'bed', 'кровать', ARRAY['Comfortable bed.', 'Make the bed.', 'King size bed.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'bed');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'bathroom', 'ванная комната', ARRAY['Private bathroom.', 'Bathroom amenities.', 'Clean bathroom.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'bathroom');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'travel_hotel', 'wifi', 'вай-фай', ARRAY['Free wifi.', 'Wifi password.', 'Connect to wifi.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'travel_hotel' AND english_word = 'wifi');
