-- Программирование
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'code', 'код', ARRAY['Write code.', 'Clean code.', 'Code review.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'code');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'programming', 'программирование', ARRAY['Programming language.', 'Programming skills.', 'Learn programming.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'programming');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'developer', 'разработчик', ARRAY['Software developer.', 'Frontend developer.', 'Web developer.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'developer');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'programmer', 'программист', ARRAY['Experienced programmer.', 'Programmer job.', 'Computer programmer.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'programmer');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'algorithm', 'алгоритм', ARRAY['Sorting algorithm.', 'Algorithm design.', 'Efficient algorithm.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'algorithm');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'function', 'функция', ARRAY['Call function.', 'Function parameter.', 'Write function.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'function');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'variable', 'переменная', ARRAY['Declare variable.', 'Variable name.', 'Variable type.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'variable');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'array', 'массив', ARRAY['Array element.', 'Create array.', 'Array index.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'array');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'object', 'объект', ARRAY['JavaScript object.', 'Object properties.', 'Create object.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'object');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'class', 'класс', ARRAY['Define class.', 'Class method.', 'Class inheritance.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'class');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'method', 'метод', ARRAY['Class method.', 'Call method.', 'Method parameter.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'method');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'loop', 'цикл', ARRAY['For loop.', 'While loop.', 'Loop iteration.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'loop');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'condition', 'условие', ARRAY['If condition.', 'Conditional statement.', 'Check condition.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'condition');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'error', 'ошибка', ARRAY['Syntax error.', 'Error message.', 'Handle error.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'error');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'tech_programming', 'debug', 'отладка, отлаживать', ARRAY['Debug code.', 'Debug mode.', 'Debugging tools.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'tech_programming' AND english_word = 'debug');

-- Приготовление пищи
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'cook', 'готовить', ARRAY['Cook dinner.', 'Cook at home.', 'Learn to cook.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'cook');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'recipe', 'рецепт', ARRAY['Follow recipe.', 'Recipe book.', 'Family recipe.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'recipe');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'ingredient', 'ингредиент', ARRAY['Fresh ingredients.', 'Main ingredient.', 'List ingredients.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'ingredient');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'kitchen', 'кухня', ARRAY['Modern kitchen.', 'Kitchen appliances.', 'Work in kitchen.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'kitchen');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'oven', 'духовка', ARRAY['Preheat oven.', 'Oven temperature.', 'Bake in oven.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'oven');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'stove', 'плита', ARRAY['Gas stove.', 'Cook on stove.', 'Electric stove.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'stove');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'pan', 'сковорода', ARRAY['Frying pan.', 'Heat the pan.', 'Non-stick pan.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'pan');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'pot', 'кастрюля', ARRAY['Soup pot.', 'Boil in pot.', 'Large pot.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'pot');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'knife', 'нож', ARRAY['Sharp knife.', 'Kitchen knife.', 'Cut with knife.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'knife');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'bowl', 'миска', ARRAY['Mixing bowl.', 'Salad bowl.', 'Pour into bowl.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'bowl');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'spoon', 'ложка', ARRAY['Wooden spoon.', 'Tablespoon.', 'Stir with spoon.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'spoon');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'fork', 'вилка', ARRAY['Use fork.', 'Fork and knife.', 'Salad fork.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'fork');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'plate', 'тарелка', ARRAY['Dinner plate.', 'Serve on plate.', 'Clean plates.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'plate');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'boil', 'кипятить', ARRAY['Boil water.', 'Boil eggs.', 'Bring to boil.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'boil');
INSERT INTO t_p7147437_shag_to_speak.word_set_items (set_id, english_word, russian_translation, examples) SELECT 'food_cooking', 'fry', 'жарить', ARRAY['Fry onions.', 'Deep fry.', 'Stir fry.'] WHERE NOT EXISTS (SELECT 1 FROM t_p7147437_shag_to_speak.word_set_items WHERE set_id = 'food_cooking' AND english_word = 'fry');
